// User reducer types
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';
export const SET_USER = 'SET_USER';
export const LOADING_USER = 'LOADING_USER';
// UI reducer types
export const SET_ERRORS = 'SET_ERRORS';
export const SET_ERRORS_LOGIN = 'SET_ERRORS_LOGIN';
export const SET_ERRORS_REGISTOR = 'SET_ERRORS_REGISTOR';
export const LOADING_UI = 'LOADING_UI';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const LOADING_DATA = 'LOADING_DATA';
export const STOP_LOADING_UI = 'STOP_LOADING_UI';
// Data reducer types
export const SET_RESTAURANTS = 'SET_RESTAURANTS';
export const SET_RESTAURANT = 'SET_RESTAURANT';
export const FILTER_RESTAURANTS = 'FILTER_RESTAURANTS';
export const POST_RESTAURANT = 'POST_RESTAURANT';
export const DELETE_RESTAURANT = 'DELETE_RESTAURANT';
export const UPDATE_RESTAURANT = 'UPDATE_RESTAURANT';